# Generated by Django 6.0.2 on 2026-08-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
