# Generated by Django 6.0.2 on 2026-08-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('carga_horaria_total', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
